version: "3.8"

services:
  # Jenkins imqge (Build artifact, send them to sonar, and to nexus, maybe triggered by gitlab ?)
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
  
  # Gitlab image (host source code, versionning etc)
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './gitlab:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'

  # SonarQube images (quality gates, security check)
  sonarqube:
    image: sonarqube
    container_name: sonar
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - './sonar/conf:/opt/sonarqube/conf'
      - './sonar/data:/opt/sonarqube/data'
      - 'sonar-extensions:/opt/sonarqube/extensions'
      - 'sonar-plugins:/opt/sonarqube/lib/bundled-plugins'

volumes:
  gitlab-logs:
  gitlab-data:
  sonar-extensions:
  sonar-plugins: