version: "3.8"

services:
    
  # Gitlab image (host source code, handle pipeline to test, upload and deploy)
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
      - '4567:4567'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        external_url 'https://gitlab'
        registry_external_url 'https://gitlab:4567'          
        registry['enable'] = true
        nginx['enable'] = true
        nginx['redirect_http_to_https'] = true
        puma['enable'] = false
        unicorn['enable'] = true
        unicorn['socket'] = '/opt/gitlab/var/unicorn/gitlab.socket'
    volumes:
      - './gitlab:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
    networks:
      - deployment-network

  # GitLab runner (to execute gitlab pipeline job)
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - './gitlab-runner:/etc/gitlab-runner:Z'
      - './gitlab/ssl:/etc/gitlab-runner/certs' # Share certificate between gitlab and gitlab runner
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - deployment-network

  # SonarQube images (quality gates, security check)
  sonarqube:
    image: sonarqube
    container_name: sonar
    restart: unless-stopped
    ports:
      - '9000:9000'
    volumes:
      - './sonar/conf:/opt/sonarqube/conf'
      - './sonar/data:/opt/sonarqube/data'
      - 'sonar-extensions:/opt/sonarqube/extensions'
      - 'sonar-plugins:/opt/sonarqube/lib/bundled-plugins'
    networks:
      - deployment-network

  # Nexus (Host builded images)
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: unless-stopped
    ports:
      - '8081:8081'
    volumes:
      - './nexus:/nexus-data'
    networks:
      - deployment-network

volumes:
  gitlab-logs:
  gitlab-data:
  sonar-extensions:
  sonar-plugins:

networks:
  deployment-network:
    name: deployment-network
    